In [17]:
#Numpy_Assignment_2::


In [18]:
#Convert a 1D array to a 2D array with 2 rows?
#Question:1
import numpy as np
arr1d=np.array([0,1,2,3,4,5,6,7,8,9])
arr1d.reshape(1,2,5)

array([[[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]]])

In [19]:
#Question:2
#How to stack two arrays vertically?
x = np.array([[0,1,2,3,4],[5,6,7,8,9]])
y = np.array([[1,1,1,1,1],[1,1,1,1,1]])
np.vstack((x,y))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [20]:
#Question:3
#How to stack two arrays horizontally?
np.hstack((x,y))

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [23]:
#Question:4
#How to convert an array of arrays into a flat 1d array?
arr2d = np.array([[0,1,2,3,4], [5,6,7,8,9]])
arr1d = arr2d.reshape(-1)
arr1d


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
#Question:5
#How to Convert higher dimension into one dimension?
arrd=np.arange(15).reshape(1,3,5)
print(arrd)
arr1d=arrd.flatten()
arr1d

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]]


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [32]:
#Question:6
#Convert one dimension to higher dimension?
arrd=np.arange(15).reshape(1,5,3)
arrd

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]]])

In [34]:
#Question:7
#Create 5x5 an array and find the square of an array?
arr=np.arange(25).reshape(1,5,5)
np.square(arr)


array([[[  0,   1,   4,   9,  16],
        [ 25,  36,  49,  64,  81],
        [100, 121, 144, 169, 196],
        [225, 256, 289, 324, 361],
        [400, 441, 484, 529, 576]]], dtype=int32)

In [38]:
#Question:8
#Create 5x6 an array and find the mean?

arr8=np.arange(30).reshape(1,5,6)
np.mean(arr)

14.5

In [39]:
#Question:9
#Find the standard deviation of the previous array in Q8?
np.std(arr8)

8.65544144839919

In [40]:
#Question:10
#Find the median of the previous array in Q8?
np.median(arr8)

14.5

In [41]:
#Question:11
#Find the transpose of the previous array in Q8?
np.transpose(arr8)

array([[[ 0],
        [ 6],
        [12],
        [18],
        [24]],

       [[ 1],
        [ 7],
        [13],
        [19],
        [25]],

       [[ 2],
        [ 8],
        [14],
        [20],
        [26]],

       [[ 3],
        [ 9],
        [15],
        [21],
        [27]],

       [[ 4],
        [10],
        [16],
        [22],
        [28]],

       [[ 5],
        [11],
        [17],
        [23],
        [29]]])

In [66]:
#Question:12
#Create a 4x4 an array and find the sum of diagonal elements?
arr=np.arange(16).reshape((4,4))
print("Original matrix is :\n",arr)
ans=arr.trace()
print("Sum of Diagonal :", ans)

Original matrix is :
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
Sum of Diagonal : 30


In [70]:
#Question:13
#Find the determinant of the previous array in Q12?
arr=np.arange(16).reshape((4,4))
print("Original matrix is :\n",arr)
ans=np.linalg.det(arr)
ans

Original matrix is :
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


-2.9582283945787796e-30

In [79]:
#Question:14
#Find the 5th and 95th percentile of an array?
arr3d=np.arange(49).reshape(7,7)
print(arr3d)
print("5th percentile of arr3d : ",np.percentile(arr,5))
print("95th percentile of arr3d : ",np.percentile(arr,95))


[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34]
 [35 36 37 38 39 40 41]
 [42 43 44 45 46 47 48]]
5th percentile of arr3d :  0.75
95th percentile of arr3d :  14.25


In [102]:
#Question:15
#How to find if a given array has any null values?
arr15=np.array([0,1,2, 23,45,44, np.nan,23])
chk=np.isnan(arr15)
chk

array([False, False, False, False, False, False,  True, False])